### ISSUE TITLE
'str' object has no attribute 'size' during training

### ISSUE THREAD

**Issue by mhoangvslev** [macabdul9/CASA-Dialogue-Act-Classifier#17]
It just happened when I run the main.py

**Comment by macabdul9** [comment]
Hi @mhoangvslev , 

Have you tried training it on your local machine or kaggle [(Notebook)](https://www.kaggle.com/eabdul/casa-dialogue-act-classifier). I think if you don't have API key it will log locally also you can comment `line 65 and 91 in Trainer.py ` and `line 20-25 and 42 in main.py` to disable the wandb logger. 

Hope this helps.

**Comment by macabdul9** [comment]
Can you paste the whole error message here and can tell me where and how are you running this?

**Comment by mhoangvslev** [comment]
I resolved the issue by downgrading transformers to 3.0.0

```bash
pip install transformers=3.0.0
```

**Comment by macabdul9** [comment]
Great, closing it.
