### ISSUE TITLE
Suspicious labels

### ISSUE THREAD

**Issue by glicerico** [macabdul9/CASA-Dialogue-Act-Classifier#2]
Hey @macabdul9 , I realize you used the `act_label_1` column in the SwDA data that you share in your repo as labels for training.
That column doesn't seem particularly good as labels, as one can see from pairs obtained from the first rows in the test data:
"Okay."  - Other
"I guess"  - Info-request:Yes-No-Question
"What kind of experience do you, do you have, then with child care ?" - Other:Segment-(multi-utterance)
These classes don't match with the [SwDA classes](https://web.stanford.edu/~jurafsky/ws97/manual.august1.html), I am not sure how they were obtained.

On the other hand, the column `act_tag` is not a good option either, as it contains 276 different classes. I think the data needs some cleaning.

**Comment by macabdul9** [comment]
Hi @glicerico, can you create a PR with clean data?

**Comment by glicerico** [comment]
Working on it ;)
